# Fraud Detection

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
dataset = pd.read_csv('creditcard.csv')
X = dataset.iloc[:, 1:29].values
y = dataset.iloc[:, 30].values

In [13]:
dataset.shape

(284807, 31)

In [14]:
dataset.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [28]:
y.shape

(284807,)

In [27]:
X.shape

(284807, 28)

In [26]:
X

array([[ -1.35980713e+00,  -7.27811730e-02,   2.53634674e+00, ...,
         -1.89114844e-01,   1.33558377e-01,  -2.10530530e-02],
       [  1.19185711e+00,   2.66150712e-01,   1.66480113e-01, ...,
          1.25894532e-01,  -8.98309900e-03,   1.47241690e-02],
       [ -1.35835406e+00,  -1.34016307e+00,   1.77320934e+00, ...,
         -1.39096572e-01,  -5.53527940e-02,  -5.97518410e-02],
       ..., 
       [  1.91956501e+00,  -3.01253846e-01,  -3.24963981e+00, ...,
         -8.73705960e-02,   4.45477200e-03,  -2.65608290e-02],
       [ -2.40440050e-01,   5.30482513e-01,   7.02510230e-01, ...,
          5.46668462e-01,   1.08820735e-01,   1.04532821e-01],
       [ -5.33412522e-01,  -1.89733337e-01,   7.03337367e-01, ...,
         -8.18267121e-01,  -2.41530900e-03,   1.36489140e-02]])

In [29]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

C:\Users\Shimeng Lin\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

In [32]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
y_pred = classifier.predict(X_test) 
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred) 
cm

array([[113710,     14],
       [    81,    118]], dtype=int64)

In [35]:
error_rate=(81+14)/(113710+14+81+118)
error_rate

0.0008338965792684533