# Fraud Detection - Logistic Regression

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# define X_train, y_train
dataset_train = pd.read_csv('training.csv')
X_train = dataset_train.iloc[:, 1:30].values
y_train = dataset_train.iloc[:, 30].values

FileNotFoundError: File b'training.csv' does not exist

In [14]:
# define X_test_1, y_test_1 
dataset_test_1 = pd.read_csv('test_01.csv')
X_test_1 = dataset_test_1.iloc[:, 1:30].values
y_test_1 = dataset_test_1.iloc[:, 30].values

# define X_test_2, y_test_2
dataset_test_2 = pd.read_csv('test_02.csv')
X_test_2 = dataset_test_2.iloc[:, 1:30].values
y_test_2 = dataset_test_2.iloc[:, 30].values

In [15]:
dataset_train.shape

(167536, 34)

In [5]:
dataset.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
2   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
3   2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728  0.476201   
4   4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   

         V8        V9    ...           V24       V25       V26       V27  \
0  0.098698  0.363787    ...      0.066928  0.128539 -0.189115  0.133558   
1  0.377436 -1.387024    ...     -1.175575  0.647376 -0.221929  0.062723   
2 -0.270533  0.817739    ...      0.141267 -0.206010  0.502292  0.219422   
3  0.260314 -0.568671    ...     -0.371427 -0.232794  0.105915  0.253844   
4  0.081213  0.464960    ...     -0.780055  0.750137 -0.257237  0.034507   

        V28  Amount  Class                                UserID  \
0 -0.021053  149.62      0  a2e2c5e2-e29c-11e7-b8f7-f7f88e75df82   
1  0.061458  123.50      0  a2e2c5e5-e29c-11e7-b8f7-f7f88e75df82   
2  0.215153   69.99      0  a2e2c5e6-e29c-11e7-b8f7-f7f88e75df82   
3  0.081080    3.67      0  a2e2c5e7-e29c-11e7-b8f7-f7f88e75df82   
4  0.005168    4.99      0  a2e2c5e8-e29c-11e7-b8f7-f7f88e75df82   

        UserType   AccntNum  
0  International  9958668.0  
1  International  6447029.0  
2  International  1599063.0  
3  International  6237481.0  
4  International  4387752.0  

[5 rows x 34 columns]

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)  
X_test_1 = sc.transform(X_test_1)
X_test_2 = sc.transform(X_test_2)

In [1]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [18]:
y_pred_1 = classifier.predict(X_test_1) 
y_pred_1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [19]:
y_pred_2 = classifier.predict(X_test_2) 
y_pred_2

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test_1, y_pred_1) 
cm_1

array([[68862,    14],
       [   34,    73]], dtype=int64)

In [23]:
error_1=(68862+73)/(68862+73+14+34)
error_1

0.9993041763912848

In [22]:
cm_2 = confusion_matrix(y_test_2, y_pred_2) 
cm_2

array([[48187,    12],
       [   29,    60]], dtype=int64)

In [24]:
error_2=(48187+60)/(48187+60+12+29)
error_2

0.999150927766733

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='gini', splitter='random')
clf.fit(X_train, y_train)

In [ ]:
y_pred_dt_1 = clf.predict(X_test_1)
y_pred_dt_1

In [ ]:
y_pred_dt_2 = clf.predict(X_test_2)
y_pred_dt_2

In [ ]:
cm_1_dt = confusion_matrix(y_test_1, y_pred_dt_1)
cm_1_dt

In [ ]:
cm_2_dt = confusion_matrix(y_test_2, y_pred_dt_2)
cm_2_dt